### ISSUE TITLE
Consider using branches instead of 2 separate folders for different versions

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/jms-api#185]
The initial contribution has the official JMS 2.0 state in one folder and the abandoned 2.1 efforts in another, see https://github.com/eclipse-ee4j/jms-api/blob/master/README.md.

That makes it harder to trace the change history of particular API elements. Ideally this should be restructured into e.g. a `2.0` branch or release tag followed by the proposed changes in `master` or something similar.

**Comment by srbala** [comment]
Here in my two cents, mix and match based your ideas.

1. Rename current `master` -> `old-master`
2. Add tag `oracle-jms-api` or `javaee-jms-api` to commit 78e7ba168f4dafb3ec45b24980d9b1149a7e8c3d, since that was orginal offical commit.
3. Create a new  orphan branch `master` so that history will be clean. Tracking from 2.0 to current will be much more visible.
4. Import `jms2.0a` folder code into master. After import create tag `jms-2.0` and branch `jms-2.0` any Erata changes with go to `jms-2.0`
5. Replace code by importing `jms2.1` folder code, since 2.1 not released no additional tag necessary, `master` will be working branch.

**Comment by keilw** [comment]
Thanks for the suggestions, this is something to discuss at least with the project lead @dblevins and maybe a few others before someone might help with it.

**Comment by srbala** [comment]
@keilw, @dblevins for your review.

Based on #188, created few branch and tags review and commits. 

Created branch `sandbox` using commit 78e7ba168f4dafb3ec45b24980d9b1149a7e8c3d. Also added tag `Initial-Contribution` to same commit.
https://github.com/srbala/jms-api/commits/sandbox

Used `sandbox` baseline, created branch `EE4J_8` with sources of `jms2.0a`,
https://github.com/srbala/jms-api/commits/EE4J_8, so JMS spec align with EE 8

Used `sandbox` baseline, created branch `dev` with sources of `jms2.1`,
https://github.com/srbala/jms-api/commits/dev

Renamed current `master` to `old-master`. Created new `master` from `EE4J_8` and merged `dev` sources
https://github.com/srbala/jms-api/commits/master

https://github.com/srbala/jms-api/releases

**Comment by keilw** [comment]
@srbala Thanks, I hope @dblevins finds the time to review and use it. He has his **birthday** today, so maybe it could be considered as sort of your present (saving him a lot of time and effort if he can reuse or merge some or all of it ;-)

**Comment by srbala** [comment]
@keilw Thanks for comments. @dblevins my birthday wishes to you.

**Comment by m0mus** [comment]
@yaminikb can you please clarify why 2.0 and 2.1 APIs are placed in different directories and not different branches. What's the advantages of doing it this way? Can if be done in different branches?

**Comment by keilw** [comment]
That was the idea.

**Comment by yaminikb** [comment]
I did bring this up with @nigeldeakin when I started preparing the jms-spec repository for donation, but we really didn't think of re-structuring at that point. We donated the folders as is. I completely agree we should re-struture this repository.

**Comment by m0mus** [comment]
Based on @yaminikb reply I believe that we can refactor it using branches instead of directories.

**Comment by keilw** [comment]
This was done
