### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jms-api#189]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

- [ ] Request JIPP for JMS

**Comment by keilw** [comment]
Before we set something up, what about https://github.com/eclipse-ee4j/jms-api/issues/185? Is the 2-folder structure the way to go, or should there be branches first?

**Comment by m0mus** [comment]
#185 is closed now.

**Comment by keilw** [comment]
Yes, the branching is done. Potentially the EE4J_J8 branch may need syncing up with the RI repository, but that does not affect the structure and existence of the branches.

**Comment by jeyvison** [comment]
Hey guys, i can help on this one if you'd like to.

**Comment by keilw** [comment]
Do you have a valid ECA?

**Comment by keilw** [comment]
Either way, I guess @m0mus knows, if "infrastructure" support is possible or you need to be voted on as committer first?

**Comment by jeyvison** [comment]
I do have a valid ECA.

**Comment by jeyvison** [comment]
Sorry @keilw , just saw you are already responsible for it. I'll get another one

**Comment by keilw** [comment]
Sure, no problem, there should be a lot without someone helping out ;-)

**Comment by m0mus** [comment]
Update from @arjantijms:
```
Build errors (mostly Javadoc based) fixed in pom, and code formatting.
Merged to EE4J_8 branch

Two jobs created. 
Simple maven job for master builds - succeeds
Release job based on shell script and using secret files; succeeds with dry-run, jars created and signed, only commit to github fails at the very last step (see https://www.eclipse.org/lists/ee4j-build/msg00294.html)
```
Closing this task as completed based on the status above.
