### ISSUE TITLE
Release pipeline and first release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jms-api#190]
We need to create a release CI/CD pipeline for this project and release the first version from Eclipse. 

- [ ] EE4J JMS maven-gpg-plugin setup (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=530304)

Use these documents as a reference:

- [How to release the first Eclipse version of projects](https://github.com/eclipse-ee4j/ee4j/wiki/How-to-release-the-first-Eclipse-version-of-projects)
- [JSONP release job](https://github.com/eclipse-ee4j/jsonp/wiki/JSONP-release-job)

**Comment by keilw** [comment]
Are you also taking the lead for JMS or inherited it from @nigeldeakin?
I'm happy to help if my Eclipse committer account has the rights for this as I do in other projects like Eclipse UOMo with the Jenkins Per Project.

**Comment by m0mus** [comment]
I am not sure that @nigeldeakin have cycles to do it. I am not taking a lead of JMS. Your help is highly appreciated. I am sure that your Eclipse account allows you to do it. If not, it's solvable.

**Comment by keilw** [comment]
I'll have a look if I am allowed to create branches with it. How about the JIPP (Jenkins Instance Per Project)? That normally is up to a project lead, so who could request one? And similar to JSON, should it be "per spec" (JSON-P, JSON-B, JMS,...) or per Eclipse project/repo?

**Comment by m0mus** [comment]
There are JIPP instances (ci.eclipse.org) and new cloud Jenkins infra available (I don't know a link to wiki) per project. As a committer you can request instances creation. 
If you want to do it for a project where you are not a committer, we can arrange all necessary rights for this contribution. Based on that you can be elected as a committer.

**Comment by m0mus** [comment]
Update from @arjantijms:
```
Build errors (mostly Javadoc based) fixed in pom, and code formatting.
Merged to EE4J_8 branch

Two jobs created. 
Simple maven job for master builds - succeeds
Release job based on shell script and using secret files; succeeds with dry-run, jars created and signed, only commit to github fails at the very last step (see https://www.eclipse.org/lists/ee4j-build/msg00294.html)
```
Closing this task as completed based on the status above.

**Comment by arjantijms** [comment]
Last step now working as well. https://github.com/eclipse-ee4j/jms-api/tree/2.0.1 was created by the jms-bot
