### ISSUE TITLE
Public Release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jms-api#219]
Last CTS runs indicate no failures in this component. It's time to make a public release. Before the release make sure that Eclipse Release Review is passed and all dependencies have been released.

**Comment by keilw** [comment]
Btw, wouldn't Glassfish 5.1 work better as Milestone, or what speaks against that? Unlike labels milestones also offer an optional release date ;-)

**Comment by arjantijms** [comment]
Release review successful: https://projects.eclipse.org/projects/ee4j.jms/reviews/2.0.2-release-review

No (Jakarta) dependencies

**Comment by arjantijms** [comment]
Release job created: 

https://jenkins.eclipse.org/jms/job/jms-api-staging-to-release

**Comment by arjantijms** [comment]
Landed in central: https://repo1.maven.org/maven2/jakarta/jms/jakarta.jms-api/2.0.2/
