### ISSUE TITLE
Prepare Jakarta Messaging for Jakarta EE 8 Release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jms-api#226]
### Tasks

- [x] Update text files
- [x] Generate "boilerplate" specification project
- [x] Make a staging release
- [x] Generate Stand-alone TCK test results
- [x] Create a PR to jakartaee/specifications repository
- [x] Update the Jakarta EE API jar by submitting a PR to the [jakartaee-api](https://github.com/eclipse-ee4j/jakartaee-api) project

See [here](https://wiki.eclipse.org/How_to_Prepare_API_Projects_to_Jakarta_EE_8_Release) for detailed instructions.

**Comment by senivam** [comment]
TCK summary for JMS:

https://jenkins.eclipse.org/jms/job/TCK_JMS_Bash/lastSuccessfulBuild/artifact/jmstck/src/com/sun/ts/tests/SUMMARY.TXT

**Comment by m0mus** [comment]
Specifications repository PR:
https://github.com/jakartaee/specifications/pull/37

**Comment by bshannon** [comment]
@senivam The TCK summary will need to be published someplace with more long term
stability than Jenkins job results.  Also, the Spec Committee has decided that only the
top lines with totals *need* to be published, although you're free to publish more if you want.

**Comment by senivam** [comment]
@bshannon you are right. And if there is any place where summaries are supposed to be copied after TCKs are done, could you please provide a reference to it? 

On the other hand jenkins' result link is quite reliable as well - that particular job is designed to provide results only for that particular API. So if it is accidentally re-run it will provide same results (they will be on the same artifact). If job fails after re-run, archived artifact remains. The only situation when summary.txt could get deleted is when job itself is deleted.

**Comment by dblevins** [comment]
I've updated this jon with the staged 2.0.3 api jar and kicked off a run.  I'm not confident in what I'm doing, so some eyes on the job are greatly appreciated:

 - https://jenkins.eclipse.org/jms/job/2_messaging-run-tck-against-staged-build/

**Comment by bshannon** [comment]
@senivam I addressed this in my [message to the spec leads list](https://www.eclipse.org/lists/jakartaee-spec-project-leads/msg00100.html).

Jenkins results just aren't stable enough.  They can be deleted because only a limited number
of old results are kept, and reference to "last successful build" results don't tell you what the
result was when you ran a particular version of the TCK against a particular version of the
implementation.

**Comment by arjantijms** [comment]
[Github pages requested](https://bugs.eclipse.org/bugs/show_bug.cgi?id=549724)

**Comment by keilw** [comment]
@arjantijms Will that fix the "Web-site details are TBD"?

**Comment by OndroMih** [comment]
I believe this is already all done, should we close this, @m0mus ?
