### ISSUE TITLE
Compatibility certification request for Jakarta Messaging

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/jms-api#239]
- [x] Organization Name ("Organization") and, if applicable, URL
  Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable)
  [Eclipse OpenMQ 5.1.4](https://eclipse-ee4j.github.io/openmq)
- [x] Specification Name, Version and download URL
   [Jakarta Messaging 2.0](https://jakarta.ee/specifications/messaging/2.0/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL
  [Jakarta Messaging TCK 2.0.0](https://download.eclipse.org/jakartaee/messaging/2.0/jakarta-messaging-tck-2.0.0.zip), SHA-256: fd175e1742a1c9e23dbc0aa0b8b881965fcead0336c121c2dac27a00a8fa113d
- [x] Public URL of TCK Results Summary
  [TCK results summary](https://eclipse-ee4j.github.io/openmq/certifications/jakarta-messaging/2.0/TCK-Results)
- [x] Any Additional Specification Certification Requirements
  None
- [x] Java runtime used to run the implementation
  Oracle JDK 1.8.0_202
- [x] Summary of the information for the certification environment, operating system, cloud, ...
  Linux
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by edbratt** [comment]
+1 looks good to me. Close?
