### ISSUE TITLE
Jakarta Messaging 3.0 Certification Request, Eclipse Open MQ 6.0.0-M3

### ISSUE THREAD

**Issue by edbratt** [eclipse-ee4j/jms-api#283]
- [x] Organization Name ("Organization") and, if applicable, URL

  Eclipse Foundation
  
- [x] Product Name, Version and download URL (if applicable)

  [Eclipse Open MQ Downloads](https://eclipse-ee4j.github.io/openmq/Downloads)
  [Eclipse OpenMQ 6.0.0M3](https://github.com/eclipse-ee4j/openmq/releases/download/6.0.0-M3-RELEASE/mq-distribution-6.0.0-M3.zip)
  
- [x] Specification Name, Version and download URL

   [Jakarta Messaging 3.0](https://jakarta.ee/specifications/messaging/3.0/)
   
- [x] TCK Version, digital SHA-256 fingerprint and download URL

  [Jakarta Messaging TCK 3.0.0](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-messaging-tck-3.0.0.zip), SHA-256: `2f5e099d9862227d9494e413ebd15033961c4271237453d1d48eb0b0005fd89c`
  
- [x] Public URL of TCK Results Summary
  [TCK results summary](https://eclipse-ee4j.github.io/openmq/certifications/jakarta-messaging/3.0/TCK-Results)

- [x] Any Additional Specification Certification Requirements
  None

- [x] Java runtime used to run the implementation

  Java(TM) SE Runtime Environment (build 1.8.0_202-b08) Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

- [x] Summary of the information for the certification environment, operating system, cloud, ...

  Alpine Linux v3.12

- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).

- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by edbratt** [comment]
Revised to reference Open MQ 6.0 M3.

**Comment by edbratt** [comment]
Revised to point at the released copy (not staged) of Open MQ

**Comment by dblevins** [comment]
Closing as this is approved
